### PR TITLE
Add API proxy (close #65)

### LINKED ISSUE #65: Make API server listen on localhost:8080 in single-node setup
This would be convenient for single-node setup.

### PR DESCRIPTION
**Pull request by errordeveloper**
This change is [Reviewable](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/67)

### CODE REVIEW

**Comment by errordeveloper** [comment]
Reviewed 4 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/weaveworks/kubernetes-anywhere/67)*

**Comment by errordeveloper** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/weaveworks/kubernetes-anywhere/67)*

**Comment by errordeveloper** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/weaveworks/kubernetes-anywhere/67)*

**Comment by peterbourgon** [comment]
I suggest a slight reordering of the steps, basically getting all setup out of the way first, then discussing how to configure kubectl, then deploying the example app. So,

1. Configuration
1.1. Weave stuff
1.2. docker run ... setup-single-node && compose -p ...
1.3. docker run ... kube-system-namespace.yaml ...
1.4. docker run ... skydns-addon-secure-v1.2 ...
2. Various ways to set up kubectl
2.1. alias kubectl docker run ... kubectl
2.2. Use kubectl --server=http://localhost:8001
2.3. Save the print-apiproxy-config output to localcluster file and use kubectl --kubeconfig
3. Deploy the guestbook app
3.1. Just use plain kubectl in all the examples here

**Comment by wstrange** [comment]
Possible enhancement: Have print-apiproxy-config print the kubectl config commands to add the weave context. 

Folks may have more than one K8s cluster - so they will not want to blow away their .kube/config

**Comment by errordeveloper** [comment]
@wstrange good point, also that's exactly the reason I've explicitly given `> ./local-cluster` as the first option. I'll think of adding what you said also.

**Comment by errordeveloper** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/weaveworks/kubernetes-anywhere/67)*

**Comment by errordeveloper** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/weaveworks/kubernetes-anywhere/67)*

**Pull request merged**
